reviews:
  profile: chill
  high_level_summary: true
  request_changes_workflow: true
  auto_review:
    enabled: false
    drafts: false
  tools:
    eslint:
      enabled: true
    gitleaks:
      enabled: true