services:
  kong:
    image: kong:3.4
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_LISTEN: "0.0.0.0:3000"
    ports:
      - "3000:3000" # Public API gateway
      - "3001:3001" # Admin API
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml
      - ./kong/kong.conf:/etc/kong/kong.conf
    networks:
      - public-net
      - internal-net
    depends_on:
      - crypto-service
      - user-service

  crypto-service:
    build:
      context: ./crypto-service
      dockerfile: Dockerfile
    container_name: crypto-service
    expose:
      - 3002
    env_file:
      - ./crypto-service/.env
    networks:
      - internal-net

  # -------------------------
  # User Service
  # -------------------------
  user-service:
    build: ./user-service
    env_file: ./user-service/.env.user
    networks:
      - internal-net
    expose:
      - 3003
    depends_on:
      - user-db
      - user-redis

  user-migrate:
    build: ./user-service
    command: ["./user-service", "-migrate", "true"]
    env_file: ./user-service/.env.user
    depends_on:
      - user-db
    networks:
      - internal-net

  # DB for User Service
  user-db:
    image: postgres:16-alpine
    container_name: user-db
    env_file: ./user-service/.env.user
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - internal-net
    expose:
      - 5432

  # Redis for User Service
  user-redis:
    image: redis:7-alpine
    container_name: user-redis
    env_file: ./user-service/.env.user
    networks:
      - internal-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      sh -c "
        if [ -n '${REDIS_PASSWORD}' ]; then
          redis-server --requirepass '${REDIS_PASSWORD}'
        else
          redis-server
        fi
      "
    expose:
      - 6379

volumes:
  user-db-data:

networks:
  public-net:   # exposed to host
  internal-net: # private between services